/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/home.module.css";
import Spinner from "../Components/Spinner";

export default function Home() {
  const [coinData, setCoinData] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    async function fetchData() {
      try {
        await fetch(
          "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false&locale=ar"
        )
          .then((response) => response.json())
          .then(setCoinData)
          .catch((error) => console.log(error));

        setLoading(false);
      } catch (error) {
        console.log(error);
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Crypto AD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <h1 className={styles.title}>🌐 Crypto AD 🌐</h1>
        </header>
        {coinData?.map((coin) => {
          return (
            <div key={coin.id} className={styles.cryptoCard}>
              <div className={styles.coinRank}>{coin.market_cap_rank}</div>
              <img
                src={coin.image}
                alt={coin.id}
                className={styles.cryptoImage}
              />

              <h1 className={styles.coinName}>{coin.id}</h1>
              <p className={styles.coinSymbol}>{coin.symbol}</p>
              <p className={styles.coinPrice}>
                Current Price: ${coin.current_price}
              </p>
              <p className={styles.coinMax}>24hs Max: ${coin.high_24h} </p>
              <p className={styles.coinLow}>24hs Low: ${coin.low_24h} </p>
            </div>
          );
        })}
        <footer className={styles.footer}>
          Copyright © 2023 Andrés Céspedes. All rights reserved.
        </footer>
      </main>
    </>
  );
}
