/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useEffect, useState } from "react";
import { Triangle } from "react-loader-spinner";
import styles from "../styles/home.module.css";

export default function Home() {
  const [coinData, setCoinData] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    async function fetchData() {
      try {
        await fetch(
          "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false&locale=ar"
        )
          .then((response) => response.json())

          .then(setCoinData)
          .catch((error) => console.log(error));

        setLoading(false);
      } catch (error) {
        console.log(error);
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Crypto AD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Crypto AD 🌐</h1>
      {loading ? (
        <Triangle
          height="80"
          width="80"
          color="#4fa94d"
          ariaLabel="triangle-loading"
          wrapperStyle={{}}
          wrapperClassName=""
          visible={true}
        />
      ) : (
        coinData?.map((coin) => {
          return (
            <div key={coin.id} className={styles.cryptoCard}>
              <img
                src={coin.image}
                alt={coin.id}
                className={styles.cryptoImage}
              />
              <div className={styles.cardContent}>
                <h1>{coin.id}</h1>
                <p>Current price: {coin.current_price}usd</p>
              </div>
            </div>
          );
        })
      )}
    </>
  );
}
